# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ajeannin <ajeannin@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/04/25 16:01:48 by ajeannin          #+#    #+#              #
#    Updated: 2024/04/25 16:15:50 by ajeannin         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME 		= megaphone
INCLUDES	=
CXX			= g++
CXXFLAGS	= -Wall -Werror -Wextra -std=c++98
SRC			= megaphone.cpp

all		: $(NAME)

$(NAME)	:
	$(CXX) $(CXXFLAGS) $(SRC) -o $(NAME)

clean	:
	rm $(NAME)
